services:
  - type: web
    name: blog-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: SECRET_KEY
        sync: false
