###  Create
POST http://localhost:5000/auth/users
Content-Type: application/json

{
    "firstName":"monu",
    "lastName":"lop",
    "email":"monu@gmail.com",
    "password":"opljjjp",
    "role":"AUTHOR",
    "profileImageUrl":"",
    "isUserActive": true
}

### login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"monu@gmail.com",
    "password":"opljjjp"
}

### logout
GET http://localhost:5000/auth/logout


### create article
POST http://localhost:5000/author-api/article
Content-Type: application/json

{
    "author":"69ccb37635f7a3f8a8f0d602",
    "title":"basics of quantum theory",
    "category":"physics",
    "content":"it tells about quantum relam"
}

### red own article
GET http://localhost:5000/author-api/article


###
PUT http://localhost:5000/author-api/articles
Content-Type: application/json

{
    "articleId":"69b3db5b4321e7c571a20d81",
    "title":"basics of quantum theory 2 ",
    "category":"physics",
    "content":"it tells about quantum relam 2 "
}

### read articles of all authors
GET http://localhost:5000/user-api/articles


### to give comments
PUT http://localhost:5000/user-api/articles
Content-Type: application/json

{
    "articleId":"69b4e43ed5159c1d39679d92",
    "comment":"bsrrhrsrhwhwrh"
}

